name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 8080:80

    steps:
     - uses: actions/checkout@v5

      - name: Wait for DVWA
        run: sleep 30

      - name: Run ZAP Baseline Scan
  run: |
    docker run --rm \
      --network host \
      -v "${{ github.workspace }}:/zap/wrk/:rw" \
      ghcr.io/zaproxy/zaproxy:stable \
      zap-baseline.py \
      -t http://localhost:8080 \
      -r zap-report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html